### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by prepor** [duct-framework/module.cljs#6]
Hello. There is no anymore `lein duct compile` (from README). It was removed here
https://github.com/duct-framework/duct/commit/fba4ad3ee9610bf3ea31cfeffc5e26a81f7bc889.

Is there some "official" way to do it, or I need to make some workaround for at least now?

Thank you.

**Comment by weavejester** [comment]
It's been replaced with `lein run :duct/compiler` in the 0.9.0 template. You can pass `lein run`, or the uberjar, a list of keys to run. This also allows for running migrations `lein run :duct/migrator`.

**Comment by prepor** [comment]
duct/exec! super cool, thank you!
