### ISSUE TITLE
Reader error on ##Inf

### ISSUE THREAD

**Issue by lambdam** [duct-framework/module.cljs#7]
Hello James,

I just created a fresh project with `lein new duct foo +cljs +site +example`

When I run `lein run :duct/compiler`, I get this error:

```
Applying optimizations :advanced to 15 sources
nov. 16, 2017 11:40:19 AM com.google.javascript.jscomp.LoggerErrorManager println
GRAVE: /tmp/foo/target/resources/foo/public/js/cljs/core.js:3579: ERROR - Parse error. primary expression expected
case ##Inf:
      ^
```

This is discussed here: https://clojurians-log.clojureverse.org/cljs-dev/2017-09-19.html and seems to be fixed in this commit: https://github.com/clojure/clojurescript/commit/26bf9a5baf30bfbe81ef98b9db300b8c9232939f

Bumping the ClojureScript dependency to the latest release (r1.9.946) should fix this.

**Comment by weavejester** [comment]
Fixed in 0.3.2
